name: .NET Framework CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore packages
      run: nuget restore ST10399080_PROG6221_POE.sln

    - name: Build solution
      run: msbuild ST10399080_PROG6221_POE.sln /p:Configuration=Release

    - name: Run tests
      run: dotnet test
